from pathlib import Path

from token_config import BOT_TOKEN

BASE_DIR = Path(__file__).resolve().parent

DATA_DIR = BASE_DIR / "data"
ML_DIR = BASE_DIR / "ml" / "artifacts"
SCRIPTS_DIR = BASE_DIR / "scripts"
TMP_DIR = BASE_DIR / "tmp"

INTENTS_PATH = DATA_DIR / "intents.json"
INTENTS_EXPANDED_PATH = DATA_DIR / "intents_expanded.json"
PRODUCTS_PATH = DATA_DIR / "products.json"
ROUTES_PATH = DATA_DIR / "dialogue_routes.json"
SMALLTALK_DATASET_PATH = DATA_DIR / "smalltalk_dataset_siberian_persona_chat.json"
DIALOGUE_TEXTS_PATH = DATA_DIR / "dialogue_texts.json"

MODEL_PATH = ML_DIR / "model.pkl"
VECTORIZER_PATH = ML_DIR / "vectorizer.pkl"
LABEL_ENCODER_PATH = ML_DIR / "label_encoder.pkl"

CONFIDENCE_THRESHOLD = 0.05
SMALLTALK_MIN_SIMILARITY = 0.12
SMALLTALK_TFIDF_NGRAM_RANGE = (1, 2)

OFFER_COOLDOWN_AFTER_DECLINE = 20
ENTRY_INTENT_THRESHOLD = 0.05
OFFER_REPLY_INTENT_THRESHOLD = 0.05
FOLLOWUP_PREFERENCE_INTENT_THRESHOLD = 0.05
COFFEE_SIGNAL_INTENT_THRESHOLD = 0.25

FREE_CHAT_MIN_TURNS_FOR_PROBE = 3
FREE_CHAT_PROBE_REPEAT_WINDOW = 15
FREE_CHAT_NEGATIVE_COFFEE_COOLDOWN = 6
FREE_CHAT_NEUTRAL_COFFEE_COOLDOWN = 5

DEFAULT_AD_TEXT_KEY = "medium"
DEFAULT_OBJECTION_AD_TEXT_KEY = "objection_expensive"
DEFAULT_FOLLOWUP_KEY = "budget_or_usage"
DEFAULT_TARGET_PRODUCT_FOLLOWUP_KEY = "which_product"

TELEGRAM_REPLY_MAX_ATTEMPTS = 3
TELEGRAM_RETRY_AFTER_FALLBACK_SECONDS = 3
TELEGRAM_SEND_RETRY_DELAY_SECONDS = 2

TELEGRAM_CONNECT_TIMEOUT = 15.0
TELEGRAM_READ_TIMEOUT = 30.0
TELEGRAM_WRITE_TIMEOUT = 30.0
TELEGRAM_POOL_TIMEOUT = 30.0
TELEGRAM_CONNECTION_POOL_SIZE = 8
TELEGRAM_UPDATES_CONNECTION_POOL_SIZE = 4

WHISPER_MODEL_SIZE = "small"
WHISPER_DEVICE = "cpu"
WHISPER_COMPUTE_TYPE = "int8"
WHISPER_LANGUAGE = "ru"
WHISPER_USE_VAD = True

TTS_VOICE = "ru-RU-SvetlanaNeural"
ENABLE_VOICE_REPLY = True

INTENT_EXPANSION_TARGET_PATTERNS = 40
SMALLTALK_DATASET_MAX_PAIRS = 25000

MODEL_TRAIN_TEST_SIZE = 0.2
MODEL_RANDOM_STATE = 42
TFIDF_NGRAM_RANGE = (1, 2)
TFIDF_MIN_DF = 1
TFIDF_MAX_DF = 0.95
LOGISTIC_REGRESSION_MAX_ITER = 2000
